include "./apts/index.yar"
include "./malicious/index.yar"
include "./other/index.yar"
include "./unknown/index.yar"
include "./FalsePositive/index.yar"
include "./ioc/index.yar"
include "./generic/index.yar"
